#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Hotel Haven - MCP Hakee Väärää Dataa
MCP näkee Klaus K:n dataa vaikka pitäisi nähdä vain Hotel Havenin
"""

def mcp_wrong_data_diagnosis():
    """Diagnosoi miksi MCP hakee väärää dataa"""
    
    print("🚨 MCP HAKEE VÄÄRÄÄ DATAA!")
    print("=" * 80)
    print()
    
    print("📊 ONGELMA:")
    print("-" * 15)
    print("• MCP näkee Toscanini.fi referral-liikennettä (254 sessions)")
    print("• Hotel Havenin GA4:ssä EI näy Toscanini.fi:tä ollenkaan")
    print("• Toscanini.fi liittyy vain Klaus K:hon")
    print("• JOHTOPÄÄTÖS: MCP hakee Klaus K:n dataa Hotel Havenin sijaan!")
    print()
    
    print("🔍 TODISTEET:")
    print("-" * 15)
    print()
    print("MCP NÄKEE:")
    print("• Toscanini.fi / referral: 254 sessions")
    print("• Sessions yhteensä: ~33,000")
    print("• Referral-kanava: 2,242 sessions")
    print()
    print("HOTEL HAVENIN GA4 (290658078):")
    print("• EI Toscanini.fi:tä referraleissa")
    print("• Sessions yhteensä: ? (kerro tämä)")
    print("• Referral-kanava: ? (kerro tämä)")
    print()
    
    print("🤔 MIKSI NÄIN TAPAHTUU:")
    print("-" * 30)
    print()
    
    print("MAHDOLLISET SYYT:")
    print()
    print("1. 🔧 YMPÄRISTÖMUUTTUJA EI PÄIVITTYNYT")
    print("   • export GA4_PROPERTY_ID=290658078 ei vaikuttanut")
    print("   • MCP käyttää edelleen vanhaa ID:tä (290818724)")
    print("   • Tarvitaan MCP:n restart tai cache-tyhjennys")
    print()
    
    print("2. 🎯 MCP:N SISÄINEN CACHE")
    print("   • MCP tallentaa dataa välimuistiin")
    print("   • Vanha data (Klaus K) on cachessa")
    print("   • Property ID vaihto ei tyhjennä cachea")
    print()
    
    print("3. 🔗 ACCOUNT-TASON OIKEUDET SEKOITTAVAT")
    print("   • MCP:llä on oikeudet molempiin property:ihin")
    print("   • API aggregoi dataa automaattisesti")
    print("   • Ei osaa erottaa property:jä toisistaan")
    print()
    
    print("4. 🌐 MCP:N KONFIGURAATIO-ONGELMA")
    print("   • MCP:n sisäinen konfiguraatio väärä")
    print("   • Kovakoodattu property ID")
    print("   • Ympäristömuuttuja ei vaikuta")
    print()
    
    print("🔧 DIAGNOOSI TESTIT:")
    print("-" * 25)
    print()
    
    print("TESTI 1: TARKISTA YMPÄRISTÖMUUTTUJA")
    print("• echo $GA4_PROPERTY_ID")
    print("• Pitäisi näyttää: 290658078")
    print()
    
    print("TESTI 2: POISTA KLAUS K OIKEUDET")
    print("• Poista MCP:ltä oikeudet Klaus K property:yn")
    print("• Testaa uudelleen")
    print("• Jos Toscanini.fi katoaa → ONGELMA RATKAISTU")
    print()
    
    print("TESTI 3: MCP RESTART")
    print("• Sammuta MCP prosessi")
    print("• Käynnistä uudelleen")
    print("• Testaa uudelleen")
    print()
    
    print("💡 TODENNÄKÖISIN SYY:")
    print("-" * 30)
    print()
    print("🎯 ACCOUNT-TASON OIKEUDET + API AGGREGAATIO")
    print()
    print("SELITYS:")
    print("• MCP:llä on Account-tason oikeudet")
    print("• GA4 API aggregoi datan kaikista property:istä")
    print("• Vaikka pyydämme Property 290658078 dataa")
    print("• API palauttaa koko Account:in datan")
    print("• Sisältää Hotel Haven + Klaus K + muut")
    print()
    print("SIKSI:")
    print("• MCP näkee Toscanini.fi:tä (Klaus K:sta)")
    print("• Hotel Havenin GA4 ei näe sitä (vain oma property)")
    print("• Luvut eivät täsmää")
    print()
    
    print("🚀 RATKAISU:")
    print("-" * 15)
    print()
    
    print("VÄLITÖN TOIMENPIDE:")
    print("1. 🔧 POISTA MCP:LTÄ KLAUS K OIKEUDET")
    print("   • Admin > Property Access Management")
    print("   • Poista ga4analysis@... Klaus K property:stä")
    print("   • Jätä vain Hotel Haven oikeudet")
    print()
    
    print("2. 🧹 TYHJENNÄ MCP CACHE")
    print("   • Restart MCP prosessi")
    print("   • Tai tyhjennä cache jos mahdollista")
    print()
    
    print("3. ✅ TESTAA UUDELLEEN")
    print("   • Hae MCP:llä referral-lähteet")
    print("   • Toscanini.fi:n pitäisi kadota")
    print("   • Luvut pitäisi täsmätä GA4:n kanssa")
    print()
    
    print("🎯 ODOTETTU TULOS:")
    print("-" * 25)
    print()
    print("KUN KLAUS K OIKEUDET POISTETTU:")
    print("• MCP ei näe enää Toscanini.fi:tä")
    print("• Sessions laskee ~33,000 → ~30,000 (arvio)")
    print("• Referral-liikenne laskee 2,242 → ~2,000")
    print("• Luvut alkavat täsmätä GA4:n kanssa")
    print()
    
    print("📊 VERTAILUTESTI:")
    print("-" * 20)
    print()
    print("ENNEN (nyt):")
    print("• MCP Sessions: ~33,000")
    print("• MCP Toscanini.fi: 254")
    print("• GA4 Sessions: ? (kerro)")
    print("• GA4 Toscanini.fi: 0")
    print()
    print("JÄLKEEN (odotettu):")
    print("• MCP Sessions: ~GA4:n luku")
    print("• MCP Toscanini.fi: 0")
    print("• GA4 Sessions: sama")
    print("• GA4 Toscanini.fi: 0")
    print()
    
    print("💭 JOHTOPÄÄTÖS:")
    print("-" * 20)
    print()
    print("MCP:n ongelma on todennäköisesti:")
    print("• Liian laajat oikeudet (Account vs Property)")
    print("• API aggregoi dataa automaattisesti")
    print("• Ei osaa rajata yhteen property:yn")
    print()
    print("RATKAISU:")
    print("• Anna MCP:lle vain Hotel Haven property oikeudet")
    print("• Poista kaikki muut property oikeudet")
    print("• Testaa että data täsmää")
    print()
    
    print("🚨 SEURAAVA ASKEL:")
    print("-" * 25)
    print("Poista MCP:ltä Klaus K oikeudet ja testaa uudelleen!")

if __name__ == "__main__":
    mcp_wrong_data_diagnosis()
