#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Hotel Haven - MCP Kalibrointisuunnitelma
Miten saada MCP:n luvut täsmäämään GA4 UI:n kanssa
"""

def mcp_calibration_plan():
    """Suunnitelma MCP:n kalibrointiin GA4 UI:n kanssa"""
    
    print("🎯 MCP KALIBROINTISUUNNITELMA")
    print("=" * 80)
    print()
    
    print("🎪 TAVOITE:")
    print("-" * 15)
    print("Saada MCP:n luvut täsmäämään GA4 UI:n kanssa,")
    print("jotta voit luottaa analyyseihin!")
    print()
    
    print("📊 NYKYINEN TILANNE:")
    print("-" * 25)
    print("• GA4 UI Room-raportti: €79,715")
    print("• MCP sessionDefaultChannelGroup: €93,771")
    print("• ERO: +€14,056 (+17.6%)")
    print("• ONGELMA: Ero liian suuri luotettavaan käyttöön")
    print()
    
    print("🔍 KALIBROINTISTRATEGIA:")
    print("-" * 30)
    print()
    
    print("VAIHE 1: GA4 UI:N TARKAN KONFIGURAATION SELVITYS")
    print("🎯 Mitä GA4 Room-raportti TARKALLEEN käyttää:")
    print()
    print("SELVITETTÄVÄ:")
    print("• Mikä on GA4:n 'Session primary channel group'?")
    print("• Onko se sama kuin 'sessionDefaultChannelGroup'?")
    print("• Vai käyttääkö GA4 jotain muuta dimensiota?")
    print("• Mikä on tarkkaan GA4:n attribuutiomalli?")
    print()
    print("TESTI: Pyydä sinua tarkistamaan GA4:stä:")
    print("1. Mene Explore → Free Form")
    print("2. Lisää Dimension: Session primary channel group")
    print("3. Lisää Metric: Item revenue")
    print("4. Lisää Filter: Item category exactly matches 'Room'")
    print("5. Date range: May 1-31, 2025")
    print("6. Vertaa tuloksia Room-raporttiin")
    print()
    
    print("VAIHE 2: MCP:N DIMENSION-TESTAUS")
    print("🔍 Testaa KAIKKI mahdolliset channel-dimensiot:")
    print()
    print("TESTATTAVAT DIMENSIOT:")
    print("• sessionDefaultChannelGroup ✅ (jo testattu)")
    print("• defaultChannelGroup")
    print("• sessionMedium")
    print("• sessionSource")
    print("• sessionSourceMedium")
    print("• sourceMedium")
    print("• medium")
    print()
    print("TAVOITE: Löytää dimensio joka antaa €79,715")
    print()
    
    print("VAIHE 3: EXPLORE-TYÖKALUN VERTAILU")
    print("🎯 Käytä GA4:n Explore-työkalua MCP:n validointiin:")
    print()
    print("TESTI-PROTOKOLLA:")
    print("1. Luo sama kysely GA4 Explore:ssa kuin MCP:ssä")
    print("2. Käytä tarkalleen samoja parametreja")
    print("3. Vertaa tuloksia rivi riviltä")
    print("4. Jos erot → selvitä syyt")
    print()
    
    print("VAIHE 4: SUODATTIMIEN TUTKINTA")
    print("🔍 Tarkista GA4:n kaikki suodattimet:")
    print()
    print("TARKISTETTAVAT TASOT:")
    print("• Account-tason suodattimet")
    print("• Property-tason suodattimet")
    print("• Data stream -suodattimet")
    print("• Sisäinen liikenne -suodattimet")
    print("• Bot-suodatus")
    print()
    print("TESTI: Luo 'Raw data' -näkymä ilman suodattimia")
    print("ja vertaa MCP:n tuloksiin")
    print()
    
    print("VAIHE 5: AIKAVYÖHYKE-SYNKRONOINTI")
    print("🕐 Varmista sama aikavyöhyke:")
    print()
    print("TOIMENPITEET:")
    print("• Tarkista GA4 Property:n aikavyöhyke-asetus")
    print("• Tarkista MCP:n aikavyöhyke (todennäköisesti UTC)")
    print("• Jos mahdollista, aseta MCP käyttämään samaa")
    print("• TAI ota huomioon 3h ero laskennassa")
    print()
    
    print("🎯 KALIBROINTIPROSESSI:")
    print("-" * 30)
    print()
    print("STEP 1: DIMENSION-LÖYTÖ")
    print("→ Testaa jokainen channel-dimensio")
    print("→ Etsi se joka antaa lähimmäksi €79,715")
    print()
    print("STEP 2: PARAMETRIEN HIENOSÄÄTÖ")
    print("→ Testaa eri metric-kombinaatioita")
    print("→ itemRevenue vs purchaseRevenue vs grossItemRevenue")
    print()
    print("STEP 3: SUODATTIMIEN SYNKRONOINTI")
    print("→ Poista GA4:stä suodattimet tai")
    print("→ Lisää MCP:hen vastaavat suodattimet")
    print()
    print("STEP 4: VALIDOINTI")
    print("→ Testaa useilla eri aikavälillä")
    print("→ Varmista <±2% ero")
    print()
    
    print("🎪 ONNISTUMISEN KRITEERIT:")
    print("-" * 35)
    print("✅ MCP:n ero GA4:een <±2%")
    print("✅ Ero on johdonmukainen eri aikavälillä")
    print("✅ Kanavien järjestys täsmää")
    print("✅ Yksittäisten kanavien erot <±5%")
    print()
    
    print("🚀 KÄYTTÖÖNOTTO:")
    print("-" * 20)
    print("KUN KALIBROINTI ONNISTUU:")
    print("• Dokumentoi tarkat parametrit")
    print("• Luo 'MCP-GA4 vastaavuustaulukko'")
    print("• Testaa säännöllisesti")
    print("• Käytä luottavaisesti analyyseihin!")
    print()
    
    print("💡 ENSIMMÄINEN TEHTÄVÄ:")
    print("-" * 30)
    print("TESTAA HETI: defaultChannelGroup (ilman 'session')")
    print()
    print("MCP-kysely:")
    print("• Dimension: defaultChannelGroup")
    print("• Filter: itemCategory = 'Room'")
    print("• Metric: itemRevenue")
    print("• Date: 2025-05-01 to 2025-05-31")
    print()
    print("Jos tämä antaa €79,715 → ONGELMA RATKAISTU!")
    print("Jos ei → jatka muiden dimensioiden testausta")

if __name__ == "__main__":
    mcp_calibration_plan()
