#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Hotel Haven - Property ID Ristiriita Löytö
MCP käyttää eri Property ID:tä kuin aiemmin luultiin
"""

def property_id_mismatch_discovery():
    """Analysoi Property ID ristiriita"""
    
    print("🚨 PROPERTY ID RISTIRIITA LÖYDETTY!")
    print("=" * 80)
    print()
    
    print("📊 PROPERTY ID VERTAILU:")
    print("-" * 30)
    print()
    print("AIEMMIN LUULIMME:")
    print(f"• Hotel Haven Property ID: 290658078")
    print(f"• MCP käyttää samaa: 290658078")
    print()
    print("TODELLISUUS:")
    print(f"• MCP käyttää: 290818724")
    print(f"• Hotel Haven: 290658078 (?)")
    print()
    
    property_mcp = "290818724"
    property_hotel = "290658078"
    
    print("🔍 ANALYYSI:")
    print("-" * 15)
    print(f"MCP Property:     {property_mcp}")
    print(f"Hotel Property:   {property_hotel}")
    print(f"ERO:              {int(property_mcp) - int(property_hotel):,}")
    print()
    
    print("🤔 MITÄ TÄMÄ TARKOITTAA:")
    print("-" * 30)
    print()
    print("MAHDOLLISET SKENAARIOT:")
    print()
    print("1. 🏨 HOTEL HAVENILLA ON USEITA PROPERTY:JA")
    print("   • 290658078: Pääsivusto (hotelhaven.fi)")
    print("   • 290818724: Toinen sivusto tai sovellus")
    print("   • MCP katsoo väärää property:ä")
    print()
    print("2. 🔄 PROPERTY ID VAIHTUNUT")
    print("   • Vanha: 290658078")
    print("   • Uusi: 290818724")
    print("   • MCP käyttää uutta, käyttäjä katsoo vanhaa")
    print()
    print("3. 🎯 VÄÄRÄ KONFIGURAATIO")
    print("   • MCP:hen konfiguroitu väärä Property ID")
    print("   • Pitäisi olla 290658078")
    print("   • Siksi luvut eivät täsmää")
    print()
    print("4. 🌐 ERI DATASTREAM")
    print("   • Sama property, eri datastream")
    print("   • Web vs App vs muut")
    print("   • Eri datastream = eri data")
    print()
    
    print("🚨 KRIITTINEN VAIKUTUS:")
    print("-" * 30)
    print()
    print("JOS MCP KATSOO VÄÄRÄÄ PROPERTY:Ä:")
    print("• KAIKKI DATA ON VÄÄRÄÄ")
    print("• Ei ole Hotel Havenin dataa ollenkaan")
    print("• Selittää 100% eron GA4:n kanssa")
    print("• Toscanini.fi kuuluu toiseen property:yn")
    print()
    
    print("💡 VÄLITÖN TOIMENPIDE:")
    print("-" * 30)
    print()
    print("TARKISTA GA4:STA:")
    print("1. 🔍 MIKÄ ON OIKEA HOTEL HAVEN PROPERTY ID?")
    print("   • Admin > Property Settings")
    print("   • Property ID numero")
    print()
    print("2. 📊 ONKO USEITA PROPERTY:JA?")
    print("   • Property selector (ylhäällä vasemmalla)")
    print("   • Montako property:ä näkyy?")
    print()
    print("3. 🎯 MIKÄ PROPERTY SISÄLTÄÄ HOTEL HAVEN DATAN?")
    print("   • Tarkista Sessions, Users toukokuulta")
    print("   • Vertaa MCP:n lukuihin")
    print()
    
    print("🔧 MCP KORJAUS:")
    print("-" * 20)
    print()
    print("JOS OIKEA PROPERTY ID ON 290658078:")
    print("• Vaihda MCP:n GA4_PROPERTY_ID")
    print("• export GA4_PROPERTY_ID=290658078")
    print("• Testaa uudelleen")
    print()
    print("JOS OIKEA PROPERTY ID ON 290818724:")
    print("• MCP on oikein")
    print("• Käyttäjä katsoo väärää property:ä")
    print("• Vaihda GA4:ssä property:ä")
    print()
    
    print("🎯 DATASTREAM TARKISTUS:")
    print("-" * 30)
    print()
    print("TARKISTA MYÖS DATASTREAM:")
    print("• Admin > Data Streams")
    print("• Montako datastream:ia on?")
    print("• Web, iOS, Android?")
    print("• Mikä on pääasiallinen datastream?")
    print()
    
    print("📊 VERTAILUTESTI:")
    print("-" * 20)
    print()
    print("TESTAA MOLEMMAT PROPERTY:T:")
    print()
    print("Property 290658078:")
    print("• Sessions toukokuu 2025: ?")
    print("• Users toukokuu 2025: ?")
    print("• Referral-liikenne: ?")
    print()
    print("Property 290818724 (MCP käyttää):")
    print("• Sessions toukokuu 2025: 33,189")
    print("• Users toukokuu 2025: 29,537")
    print("• Referral-liikenne: 2,242")
    print("• Toscanini.fi: 254 sessions")
    print()
    
    print("🎯 RATKAISUN LÖYTÄMINEN:")
    print("-" * 30)
    print()
    print("KUMPI PROPERTY SISÄLTÄÄ:")
    print("• Hotel Haven varaukset?")
    print("• Oikeat kanavat (Paid Social, Organic Search)?")
    print("• Järkevät luvut hotellille?")
    print()
    print("SE ON OIKEA PROPERTY!")
    print()
    
    print("💭 JOHTOPÄÄTÖS:")
    print("-" * 20)
    print()
    print("Tämä voi selittää:")
    print("• Miksi Toscanini.fi näkyy MCP:ssä mutta ei GA4:ssä")
    print("• Miksi kaikki luvut eroavat")
    print("• Miksi MCP:n data vaikuttaa 'vieraalta'")
    print()
    print("KERRO:")
    print("1. Mikä on Hotel Havenin oikea Property ID?")
    print("2. Montako property:ä sinulla on?")
    print("3. Mitkä ovat Sessions/Users luvut molemmissa?")

if __name__ == "__main__":
    property_id_mismatch_discovery()
