#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Hotel Haven - Tekninen Debuggausopas
Evästehallintaongelmien tekninen selvittäminen
"""

def create_technical_checklist():
    """Luo tekninen tarkistuslista"""
    
    print("🔧 HOTEL HAVEN - TEKNINEN DEBUGGAUSOPAS")
    print("=" * 80)
    print("Evästehallintamuutosten tekninen ongelmanratkaisu")
    print("=" * 80)
    print()
    
    print("🚨 KRIITTINEN ONGELMA:")
    print("GA4-liikenne pudonnut 50% evästehallintamuutosten jälkeen")
    print("Todennäköinen syy: Tekninen implementointiongelma")
    print()
    
    print("🔍 VÄLITÖN TEKNINEN TARKISTUS")
    print("=" * 60)
    print()
    
    print("1. 🍪 COOKIEPRO-ASETUKSET")
    print("-" * 30)
    print("□ Kirjaudu CookiePro-hallintapaneeliin")
    print("□ Tarkista 'Analytics' -kategorian asetukset:")
    print("  • Onko Google Analytics sallittu oletuksena? (Pitäisi olla EI)")
    print("  • Latautuuko GA4 vasta hyväksynnän jälkeen? (Pitäisi olla KYLLÄ)")
    print("  • Onko Consent Mode käytössä? (Pitäisi olla KYLLÄ)")
    print("□ Tarkista evästebannerin näkyvyys:")
    print("  • Näkyykö banneri ensikäynnillä?")
    print("  • Toimivatko hyväksy/hylkää -painikkeet?")
    print("□ Testaa eri selaimilla (Chrome, Firefox, Safari)")
    print()
    
    print("2. 🏷️ GOOGLE TAG MANAGER")
    print("-" * 30)
    print("□ Avaa GTM-työtila (tagmanager.google.com)")
    print("□ Tarkista GA4-tagin asetukset:")
    print("  • Onko Consent Mode käytössä?")
    print("  • Ovatko 'ad_storage' ja 'analytics_storage' oikein?")
    print("□ Tarkista liipaisinten asetukset:")
    print("  • Lataako GA4-tagi sivun latauksen yhteydessä?")
    print("  • Onko evästehyväksyntä-liipaisin oikein?")
    print("□ Testaa Preview-tilassa:")
    print("  • Näkyykö GA4-tagi Debug-näkymässä?")
    print("  • Laukeaako tagi evästehyväksynnän jälkeen?")
    print()
    
    print("3. 📊 GA4-ASETUKSET")
    print("-" * 30)
    print("□ Kirjaudu GA4-tilille (analytics.google.com)")
    print("□ Tarkista Real-time -raportti:")
    print("  • Näkyykö liikennettä reaaliajassa?")
    print("  • Onko liikenne normaalia tasoa?")
    print("□ Tarkista Debug View:")
    print("  • Lähettääkö sivusto tapahtumia?")
    print("  • Näkyvätkö consent-tilat oikein?")
    print("□ Tarkista Data Streams:")
    print("  • Onko Enhanced Measurement käytössä?")
    print("  • Toimiiko mittauskoodi?")
    print()

def create_browser_testing_guide():
    """Luo selaimen testausopas"""
    
    print("🌐 SELAIMEN TESTAUSOPAS")
    print("=" * 60)
    print()
    
    print("🔍 MANUAALINEN TESTAUS")
    print("-" * 30)
    print()
    
    print("VAIHE 1: Perustestaus")
    print("□ Avaa sivusto incognito/private-tilassa")
    print("□ Avaa Developer Tools (F12)")
    print("□ Mene Network-välilehdelle")
    print("□ Päivitä sivu (F5)")
    print("□ Etsi 'google-analytics' tai 'gtag' -pyyntöjä")
    print("□ Huomio: Pitäisikö näkyä pyyntöjä ENNEN evästehyväksyntää?")
    print()
    
    print("VAIHE 2: Evästehyväksyntätesti")
    print("□ Hyväksy evästeet")
    print("□ Tarkista Network-välilehdeltä uudet pyynnöt")
    print("□ Pitäisi näkyä google-analytics.com -pyyntöjä")
    print("□ Navigoi toiselle sivulle")
    print("□ Tarkista lähtevätkö pageview-tapahtumat")
    print()
    
    print("VAIHE 3: Console-virheiden tarkistus")
    print("□ Avaa Console-välilehti")
    print("□ Etsi JavaScript-virheitä (punaiset viestit)")
    print("□ Erityisesti:")
    print("  • gtag is not defined")
    print("  • Google Analytics errors")
    print("  • CookiePro-virheet")
    print()
    
    print("VAIHE 4: Consent Mode -testi")
    print("□ Avaa Console ja kirjoita:")
    print("  > gtag('get', 'GA_MEASUREMENT_ID', 'consent')")
    print("□ Pitäisi näyttää consent-tilat:")
    print("  • ad_storage: 'granted' tai 'denied'")
    print("  • analytics_storage: 'granted' tai 'denied'")
    print()

def create_cookiepro_debugging():
    """Luo CookiePro-debuggausopas"""
    
    print("🍪 COOKIEPRO DEBUGGAUS")
    print("=" * 60)
    print()
    
    print("🔧 YLEISIMMÄT ONGELMAT JA RATKAISUT")
    print("-" * 40)
    print()
    
    print("ONGELMA 1: GA4 ei lataudu lainkaan")
    print("🔍 Syy: GA4-tagi asetettu 'Analytics' -kategoriaan")
    print("✅ Ratkaisu:")
    print("   1. CookiePro → Cookie Categories")
    print("   2. Analytics → Custom Scripts")
    print("   3. Poista GA4-koodi täältä")
    print("   4. Aseta GA4 latautumaan GTM:n kautta Consent Modella")
    print()
    
    print("ONGELMA 2: Consent Mode ei toimi")
    print("🔍 Syy: Väärät Consent Mode -asetukset")
    print("✅ Ratkaisu:")
    print("   1. GTM → GA4-tagi → Advanced Settings")
    print("   2. Lisää Consent Mode -parametrit:")
    print("      - ad_storage: denied (oletuksena)")
    print("      - analytics_storage: denied (oletuksena)")
    print("   3. Lisää evästehyväksyntä-liipaisin")
    print("   4. Päivitä consent-tilat hyväksynnän jälkeen")
    print()
    
    print("ONGELMA 3: Evästebanneri ei näy")
    print("🔍 Syy: Väärät geo-asetukset tai kohdistus")
    print("✅ Ratkaisu:")
    print("   1. CookiePro → Geolocation")
    print("   2. Tarkista Suomi-asetukset")
    print("   3. Testaa VPN:llä eri maista")
    print()
    
    print("ONGELMA 4: Evästekategoriat väärät")
    print("🔍 Syy: GA4 väärässä kategoriassa")
    print("✅ Ratkaisu:")
    print("   1. CookiePro → Cookie Categories")
    print("   2. Siirrä kaikki tracking 'Analytics' -kategoriaan")
    print("   3. Älä laita mitään 'Strictly Necessary' -kategoriaan")
    print()

def create_consent_mode_implementation():
    """Luo Consent Mode -implementointiopas"""
    
    print("📋 CONSENT MODE V2 IMPLEMENTOINTI")
    print("=" * 60)
    print()
    
    print("🚀 NOPEA RATKAISU - GTM-KOODI")
    print("-" * 40)
    print()
    
    print("1. LISÄÄ TÄMÄ KOODI GTM:ään (Custom HTML -tagi)")
    print("   Liipaisin: All Pages")
    print()
    print("```html")
    print("<!-- Consent Mode v2 Default Settings -->")
    print("<script>")
    print("  // Aseta oletusasetukset ENNEN gtag-kirjaston lataamista")
    print("  window.dataLayer = window.dataLayer || [];")
    print("  function gtag(){dataLayer.push(arguments);}")
    print("  ")
    print("  gtag('consent', 'default', {")
    print("    'ad_storage': 'denied',")
    print("    'ad_user_data': 'denied',")
    print("    'ad_personalization': 'denied',")
    print("    'analytics_storage': 'denied',")
    print("    'functionality_storage': 'denied',")
    print("    'personalization_storage': 'denied',")
    print("    'security_storage': 'granted',")
    print("    'wait_for_update': 500")
    print("  });")
    print("</script>")
    print("```")
    print()
    
    print("2. LISÄÄ EVÄSTEHYVÄKSYNTÄ-TAGI")
    print("   Liipaisin: CookiePro OptanonWrapper")
    print()
    print("```html")
    print("<script>")
    print("  // Päivitä consent-tilat hyväksynnän jälkeen")
    print("  function OptanonWrapper() {")
    print("    if (OnetrustActiveGroups.indexOf('C0002') > -1) {")
    print("      gtag('consent', 'update', {")
    print("        'analytics_storage': 'granted'")
    print("      });")
    print("    }")
    print("    ")
    print("    if (OnetrustActiveGroups.indexOf('C0004') > -1) {")
    print("      gtag('consent', 'update', {")
    print("        'ad_storage': 'granted',")
    print("        'ad_user_data': 'granted',")
    print("        'ad_personalization': 'granted'")
    print("      });")
    print("    }")
    print("  }")
    print("</script>")
    print("```")
    print()
    
    print("3. MUOKKAA GA4-TAGIA")
    print("   □ Poista kaikki Consent-asetukset GA4-tagista")
    print("   □ Anna Consent Moden hoitaa kaikki asetukset")
    print("   □ Varmista että tagi laukeaa kaikilla sivuilla")
    print()

def create_testing_scenarios():
    """Luo testausskenaariot"""
    
    print("🧪 TESTAUSSKENAARIOT")
    print("=" * 60)
    print()
    
    print("SKENAARIO 1: Uusi käyttäjä (ei evästeitä)")
    print("-" * 45)
    print("□ Avaa sivusto incognito-tilassa")
    print("□ Odotettu: Evästebanneri näkyy")
    print("□ Odotettu: GA4 EI lähetä dataa (denied-tilassa)")
    print("□ Tarkista Console: gtag('get', 'GA_MEASUREMENT_ID', 'consent')")
    print("□ Pitäisi näyttää: analytics_storage: 'denied'")
    print()
    
    print("SKENAARIO 2: Käyttäjä hyväksyy evästeet")
    print("-" * 45)
    print("□ Klikkaa 'Hyväksy kaikki' -painiketta")
    print("□ Odotettu: GA4 alkaa lähettää dataa")
    print("□ Tarkista Network: google-analytics.com -pyynnöt")
    print("□ Tarkista Console: analytics_storage: 'granted'")
    print()
    
    print("SKENAARIO 3: Käyttäjä hylkää evästeet")
    print("-" * 45)
    print("□ Klikkaa 'Hylkää' tai sulje banneri")
    print("□ Odotettu: GA4 EI lähetä dataa")
    print("□ Tarkista: Ei google-analytics.com -pyyntöjä")
    print("□ Tarkista Console: analytics_storage: 'denied'")
    print()
    
    print("SKENAARIO 4: Palaava käyttäjä (evästeet hyväksytty)")
    print("-" * 45)
    print("□ Palaa sivustolle (ei incognito)")
    print("□ Odotettu: Ei evästebanneria")
    print("□ Odotettu: GA4 lähettää dataa heti")
    print("□ Tarkista: Välitön google-analytics.com -pyyntö")
    print()

def create_monitoring_dashboard():
    """Luo seurantaohje"""
    
    print("📊 SEURANNAN PYSTYTTÄMINEN")
    print("=" * 60)
    print()
    
    print("🎯 SEURATTAVAT MITTARIT")
    print("-" * 30)
    print()
    
    print("1. GA4 REAL-TIME")
    print("□ Seuraa päivittäin klo 10-16")
    print("□ Vertaile edelliseen viikkoon")
    print("□ Huomioi viikonpäiväerot")
    print()
    
    print("2. EVÄSTEHYVÄKSYNTÄASTE")
    print("□ CookiePro → Reports")
    print("□ Tavoite: >70% hyväksyntäaste")
    print("□ Seuraa päivittäin")
    print()
    
    print("3. KANAVITTAINEN SEURANTA")
    print("□ Organic Search: Pitäisi palautua nopeasti")
    print("□ Direct: Hitain palautuminen")
    print("□ Paid: Riippuu kampanja-asetuksista")
    print()
    
    print("4. TEKNISTEN VIRHEIDEN SEURANTA")
    print("□ Google Search Console: Indeksointivirheet")
    print("□ GA4 Debug View: Tapahtumien lähetys")
    print("□ GTM Preview: Tagien toiminta")
    print()

if __name__ == "__main__":
    create_technical_checklist()
    create_browser_testing_guide()
    create_cookiepro_debugging()
    create_consent_mode_implementation()
    create_testing_scenarios()
    create_monitoring_dashboard()
    
    print("🎯 YHTEENVETO - SEURAAVAT ASKELEET")
    print("=" * 80)
    print()
    print("1. 🔥 VÄLITTÖMÄT TOIMET (tänään):")
    print("   • Tarkista CookiePro-asetukset")
    print("   • Testaa sivusto incognito-tilassa")
    print("   • Tarkista GTM Debug View")
    print()
    print("2. 🛠️ TEKNINEN KORJAUS (1-2 päivää):")
    print("   • Implementoi Consent Mode v2")
    print("   • Testaa kaikki skenaariot")
    print("   • Seuraa GA4 Real-time -dataa")
    print()
    print("3. 📊 SEURANTA (jatkuva):")
    print("   • Päivittäinen GA4-seuranta")
    print("   • Evästehyväksyntäasteen seuranta")
    print("   • Kanavittainen analyysi")
    print()
    print("🚀 ODOTETTU TULOS: 20-30% liikenteen palautuminen 1-2 viikossa!")
